apiVersion: v1
kind: Service
metadata:
    name: trade-mate-backend-service
spec:
    selector:
        app: trade-mate-backend
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: LoadBalancer
